### ISSUE TITLE
Uppdatera länken till rättsinfo som visas vid inloggning

### ISSUE THREAD

**Issue by helelun** [rinfo/fst#105]
I Domstolsverkets instans av FST leder länken längst ned till rättsinfoprojektet till fel sida. 

![1xx lnk i fst](https://cloud.githubusercontent.com/assets/6142669/3216323/7ee02ece-efce-11e3-95e1-a028ccc62a47.png)

**Comment by kamidev** [comment]
Implementerat. Bör framgå av skärmbild i användarhandledningen.

**Comment by helelun** [comment]
Rätt länk och OK i användarhandledningen.
