### ISSUE TITLE
Ersätt begreppet "Celex" med "EU-rättsreferens"

### ISSUE THREAD

**Issue by kamidev** [rinfo/fst#115]
Implementerat och ska framgå av användarhandledningen.

**Comment by helelun** [comment]
Celex kvarstår på ett ställe i FST, och i användarhandledningen, i menyn där man matar in en ny föreskrift.

![skarmavbild 2016-11-10 kl 12 01 44](https://cloud.githubusercontent.com/assets/6142669/20174383/db87b6dc-a73d-11e6-9713-2c7e346566dd.png)

**Comment by kamidev** [comment]
Noterat. Ska se om vi kan fixa det.

**Comment by kamidev** [comment]
Bör vara fixat på testsajten nu.

**Comment by helelun** [comment]
OK i FST och i användarhandledning.
