### ISSUE TITLE
Atom-flödets updated ändras inte vid ändring av feed-metadata

### ISSUE THREAD

**Issue by niklasl** [rinfo/fst#46]
Datumet i atom-flödets updated-fält är direkt taget från det nyaste entryt. Detta gör ingenting för insamling av poster, men innebär att t.ex. ändringar av de kontaktuppgifter och dylikt som anges i flödets metadata inte reflekteras i detta datum.

**Comment by kamidev** [comment]
För närvarande finns det inget sätt att uppdatera alla uppgifter som krävs via användargränssnittet. Flödets URL, kontaktuppgifter et cetera sätts istället via konfigurationsfiler när FST installeras för första gången. 

Kanske räcker det att sköta eventuella ändringar på samma sätt? Detta är dock en rutin som bör dokumenteras.
