### ISSUE TITLE
Visa "FST" istället för "fs_doc" som grupperande rubrik på förstasidan

### ISSUE THREAD

**Issue by kamidev** [rinfo/fst#66]
Detta gäller bl a rubriker och breadcrumbs på admin:s indexsida. Enklaste lösningen är förmodligen att implementera en egen templatetag i filen adminfilters.py. Se http://snipt.net/chrisdpratt/overriding-app_label-in-django-admin/

**Comment by kamidev** [comment]
Originalkravet har ändrats. Rubriken "fs_doc" ska istället ändras till "FST".

**Comment by kamidev** [comment]
I och med uppgradring av Django finns det en enklare lösning.

**Comment by kamidev** [comment]
Detta ska synas i användarhandboken.

**Comment by helelun** [comment]
OK i användarhandledningen.
